@echo off
REM Portfolio Setup Script for Windows
REM This script sets up the development environment for the portfolio project

echo 🚀 Setting up Portfolio Project...

REM Check if Node.js is installed
node --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Node.js is not installed. Please install Node.js first.
    echo    Download from: https://nodejs.org/
    pause
    exit /b 1
)

REM Check if npm is installed
npm --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ npm is not installed. Please install npm first.
    pause
    exit /b 1
)

echo ✅ Node.js and npm are installed

REM Install dependencies
echo 📦 Installing dependencies...
npm install --legacy-peer-deps

REM Check if installation was successful
if %errorlevel% neq 0 (
    echo ❌ Failed to install dependencies
    pause
    exit /b 1
)

echo ✅ Dependencies installed successfully

REM Create environment file if it doesn't exist
if not exist .env.local (
    echo 📝 Creating environment file...
    (
        echo # Portfolio Environment Variables
        echo # Add your environment variables here
        echo.
        echo # Next.js
        echo NEXT_PUBLIC_APP_URL=http://localhost:3000
        echo.
        echo # Analytics ^(Optional^)
        echo NEXT_PUBLIC_GA_ID=
        echo.
        echo # Contact Form ^(Optional^)
        echo CONTACT_FORM_EMAIL=
        echo.
        echo # Other configurations
        echo NODE_ENV=development
    ) > .env.local
    echo ✅ Environment file created ^(.env.local^)
) else (
    echo ✅ Environment file already exists
)

REM Create .gitignore if it doesn't exist
if not exist .gitignore (
    echo 📝 Creating .gitignore file...
    (
        echo # Dependencies
        echo node_modules/
        echo .pnp
        echo .pnp.js
        echo.
        echo # Testing
        echo coverage/
        echo.
        echo # Next.js
        echo .next/
        echo out/
        echo build/
        echo dist/
        echo.
        echo # Production
        echo .env.local
        echo .env.development.local
        echo .env.test.local
        echo .env.production.local
        echo.
        echo # Debug
        echo npm-debug.log*
        echo yarn-debug.log*
        echo yarn-error.log*
        echo.
        echo # Runtime data
        echo pids
        echo *.pid
        echo *.seed
        echo *.pid.lock
        echo.
        echo # Directory for instrumented libs generated by jscoverage/JSCover
        echo lib-cov
        echo.
        echo # Coverage directory used by tools like istanbul
        echo coverage
        echo *.lcov
        echo.
        echo # nyc test coverage
        echo .nyc_output
        echo.
        echo # Dependency directories
        echo node_modules/
        echo jspm_packages/
        echo.
        echo # Optional npm cache directory
        echo .npm
        echo.
        echo # Optional eslint cache
        echo .eslintcache
        echo.
        echo # Microbundle cache
        echo .rpt2_cache/
        echo .rts2_cache_cjs/
        echo .rts2_cache_es/
        echo .rts2_cache_umd/
        echo.
        echo # Optional REPL history
        echo .node_repl_history
        echo.
        echo # Output of 'npm pack'
        echo *.tgz
        echo.
        echo # Yarn Integrity file
        echo .yarn-integrity
        echo.
        echo # parcel-bundler cache ^(https://parceljs.org/^)
        echo .cache
        echo .parcel-cache
        echo.
        echo # next.js build output
        echo .next
        echo.
        echo # nuxt.js build output
        echo .nuxt
        echo.
        echo # vuepress build output
        echo .vuepress/dist
        echo.
        echo # Serverless directories
        echo .serverless/
        echo.
        echo # FuseBox cache
        echo .fusebox/
        echo.
        echo # DynamoDB Local files
        echo .dynamodb/
        echo.
        echo # TernJS port file
        echo .tern-port
        echo.
        echo # Stores VSCode versions used for testing VSCode extensions
        echo .vscode-test
        echo.
        echo # System files
        echo .DS_Store
        echo Thumbs.db
        echo.
        echo # IDE files
        echo .vscode/
        echo .idea/
        echo *.swp
        echo *.swo
        echo *~
        echo.
        echo # Logs
        echo logs
        echo *.log
    ) > .gitignore
    echo ✅ .gitignore file created
) else (
    echo ✅ .gitignore file already exists
)

echo.
echo 🎉 Setup completed successfully!
echo.
echo 📋 Next steps:
echo    1. Review and update .env.local if needed
echo    2. Run 'npm run dev' to start the development server
echo    3. Open http://localhost:3000 in your browser
echo.
echo 📚 Useful commands:
echo    npm run dev     - Start development server
echo    npm run build   - Build for production
echo    npm run start   - Start production server
echo    npm run lint    - Run linting
echo.
echo 🌟 Happy coding!
pause
