const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Portfolio Setup Script (Node.js version)
// This script sets up the development environment for the portfolio project

console.log('🚀 Setting up Portfolio Project...');

// Check if Node.js is installed
try {
  const nodeVersion = execSync('node --version', { encoding: 'utf8' }).trim();
  console.log(`✅ Node.js is installed (${nodeVersion})`);
} catch (error) {
  console.error('❌ Node.js is not installed. Please install Node.js first.');
  console.error('   Download from: https://nodejs.org/');
  process.exit(1);
}

// Check if npm is installed
try {
  const npmVersion = execSync('npm --version', { encoding: 'utf8' }).trim();
  console.log(`✅ npm is installed (${npmVersion})`);
} catch (error) {
  console.error('❌ npm is not installed. Please install npm first.');
  process.exit(1);
}

// Install dependencies
console.log('📦 Installing dependencies...');
try {
  execSync('npm install --legacy-peer-deps', { stdio: 'inherit' });
  console.log('✅ Dependencies installed successfully');
} catch (error) {
  console.error('❌ Failed to install dependencies');
  process.exit(1);
}

// Install jsrepo globally
console.log('🔧 Installing jsrepo globally...');
try {
  execSync('npm install -g jsrepo', { stdio: 'inherit' });
  console.log('✅ jsrepo installed successfully');
} catch (error) {
  console.log('⚠️  Could not install jsrepo globally (may require admin rights)');
  console.log('   You can install it manually with: npm install -g jsrepo');
}

// Add jsrepo components (optional - uncomment if needed)
console.log('🎨 Setting up jsrepo components...');
try {
  // Add Cubes component
  execSync('npx jsrepo@latest add https://reactbits.dev/r/Cubes-JS-CSS', { stdio: 'inherit' });
  console.log('✅ Cubes component added');
} catch (error) {
  console.log('⚠️  Could not add Cubes component (may already exist)');
}

try {
  // Add ScrollStack component
  execSync('npx jsrepo@latest add https://reactbits.dev/r/ScrollStack-JS-CSS', { stdio: 'inherit' });
  console.log('✅ ScrollStack component added');
} catch (error) {
  console.log('⚠️  Could not add ScrollStack component (may already exist)');
}

// Create environment file if it doesn't exist
const envPath = path.join(process.cwd(), '.env.local');
if (!fs.existsSync(envPath)) {
  console.log('📝 Creating environment file...');
  const envContent = `# Portfolio Environment Variables
# Add your environment variables here

# Next.js
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Analytics (Optional)
NEXT_PUBLIC_GA_ID=

# Contact Form (Optional)
CONTACT_FORM_EMAIL=

# Other configurations
NODE_ENV=development

# Add your custom environment variables below
# NEXT_PUBLIC_API_KEY=
# NEXT_PUBLIC_DATABASE_URL=
`;
  fs.writeFileSync(envPath, envContent);
  console.log('✅ Environment file created (.env.local)');
} else {
  console.log('✅ Environment file already exists');
}

// Create .gitignore if it doesn't exist
const gitignorePath = path.join(process.cwd(), '.gitignore');
if (!fs.existsSync(gitignorePath)) {
  console.log('📝 Creating .gitignore file...');
  const gitignoreContent = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Next.js
.next/
out/
build/
dist/

# Production
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Dependency directories
node_modules/
jspm_packages/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# next.js build output
.next

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# System files
.DS_Store
Thumbs.db

# IDE files
.vscode/
.idea/
*.swp
*.swo
*~

# Logs
logs
*.log
`;
  fs.writeFileSync(gitignorePath, gitignoreContent);
  console.log('✅ .gitignore file created');
} else {
  console.log('✅ .gitignore file already exists');
}

// Check if package.json has start script
const packageJsonPath = path.join(process.cwd(), 'package.json');
try {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  if (!packageJson.scripts || !packageJson.scripts.start) {
    console.log('⚠️  Warning: No \'start\' script found in package.json');
    console.log('   Make sure your package.json has: "start": "next start"');
  }
} catch (error) {
  console.log('⚠️  Warning: Could not read package.json');
}

console.log('\n🎉 Setup completed successfully!');
console.log('\n📋 Next steps:');
console.log('   1. Review and update .env.local if needed');
console.log('   2. Run \'npm run dev\' to start the development server');
console.log('   3. Open http://localhost:3000 in your browser');
console.log('\n📚 Useful commands:');
console.log('   npm run dev     - Start development server');
console.log('   npm run build   - Build for production');
console.log('   npm run start   - Start production server');
console.log('   npm run lint    - Run linting');
console.log('\n🌟 Happy coding!');
